apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  selector:
    app: kubesimple
  ports: 
    - port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeappsimples
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: kubesimple
  template:
    metadata:
      labels:
        app: kubesimple
    spec:
      containers:
        - name: kubecontainer
          image: franortega01/simpleapi:1.0.0
          ports:
            - cointainerPort: 8080
          imagePullPolicy: Always

