const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASES_ERROR: 3,
    PRODUCT_NOT_FOUND_ERROR: 4,
    CREATE_PRODUCT_ERROR:5,
    CART_NOT_FOUND_ERROR:6,
    ADD_PRODUCT_IN_CART_ERROR: 7,
    USER_NOT_FOUND_ERROR:11,
    CREATE_USER_ERROR: 12,
    CREATE_CART_ERROR:13,
}

export default EErrors;